### ISSUE TITLE
Support for locking

### ISSUE THREAD

**Issue by michael-donat** [michael-donat/php-vfs#24]

**Comment by michael-donat** [comment]
#19 for details

**Comment by milesj** [comment]
Any progress on this? Blowing up my Travis :P 

https://travis-ci.org/titon/io

**Comment by michael-donat** [comment]
Can't really commit to anything particular now - workload rumped up ;)

**Comment by milesj** [comment]
If I have some free time, I'll fork it and take a look, no rush!

**Comment by mattzuba** [comment]
@milesj Did you ever have a chance to look into this?  I have some tests failing due to file locking in the code I'm testing.

Edit: Looks like it could be because I'm using file_get_contents, which doesn't support LOCK_EX on non-regular files... vfsStream has the same issue: https://github.com/mikey179/vfsStream/issues/44

**Comment by milesj** [comment]
I have not had time yet. Got sidetracked with other projects.

**Comment by milesj** [comment]
:+1:
