### ISSUE TITLE
mkdir permission check fails

### ISSUE THREAD

**Issue by twifty** [michael-donat/php-vfs#49]
When `mkdir` is supplied with a hierarchy, the permission checking is skipped, which allows the directory to be created regardless.

```php
$fs->createDirectory('/foo');

chown($fs->path('/foo'), 'root');
mkdir($fs->path('/foo').'/bar/baz', 0777, true); // <-- Should fail
```

I see internally, `Wrapper::mkdir` line 354, calls `dirname('/foo/bar/baz')` then `nodeAt('/foo/bar')` throws, which prematurely exits the loop allowing the dir to be created without permission check.

**Comment by peter279k** [comment]
I cannot find the current line of codes you mention.

I think the `Wrapper` source codes are changed, but I'm not sure this issue has been resolved.

When I try to reproduce your issue you mention, `mkdir($fs->path('/foo').'/bar/baz', 0777, true);` will return `true`.

Maybe you can create related PR or suggested code changes to help me know where the problem is :).

**Comment by twifty** [comment]
Wowzer, a 3 year old bug. I'd guess it has probably been fixed since I reported it. I've also moved away from PHP development, so I'm not in a position to easily reproduce it. I guess this can be closed.

(I've also since discovered that linking to the commit and line works wonders ;-) )
